main:
  push:
    - stages:
        - name: sync to github
          image: tencentcom/git-sync
          imports: https://cnb.cool/saitolers/SECRETS/-/blob/main/secrets.yml
          settings:
            target_url: https://github.com/Saitoler/WechatPosts2Md.git
            auth_type: https
            username: $SYNC_GIT_USERNAME
            password: $SYNC_GIT_TOKEN